//Define Clock source
#define MCU_CLOCK_SOURCE      
#define MCU_CLOCK_SOURCE_HIRC  // HXT, LXT, HIRC, LIRC
#define MCU_CLOCK_SOURCE_LIRC 
#define MCU_CLOCK_FREQUENCY   50000000  //Hz

//Define MCU Interfaces
#define MCU_INTERFACE_WDT
#define WDT_CLOCK_SOURCE_LXT // LIRC, HCLK_DIV2048, LXT  

#define MCU_INTERFACE_SPI3
#define SPI_CLOCK_SOURCE_HCLK
#define PIN_SPI3_SCLK_PD9
#define PIN_SPI3_MISO0_PD10
#define PIN_SPI3_MOSI0_PD11
//#define PIN_SPI3_MISO1_PD12
//#define PIN_SPI3_MOSI1_PD13
