
//Define Clock source
#define MCU_CLOCK_SOURCE      
#define MCU_CLOCK_SOURCE_HXT // HXT, LXT, HIRC, LIRC 
#define MCU_CLOCK_FREQUENCY   48000000  //Hz

//Define MCU Interfaces
#define MCU_INTERFACE_ADC
#define ADC_CLOCK_SOURCE_HXT // HXT, LXT, PLL, HIRC, HCLK
#define ADC_CLOCK_DIVIDER    3
#define PIN_ADC0_PA0
#define PIN_ADC1_PA1
#define PIN_ADC2_PA2
#define PIN_ADC3_PA3
#define PIN_ADC4_PA4
#define PIN_ADC5_PA5
#define PIN_ADC6_PA6
#define PIN_ADC7_PA7
#define ADC_CHANNEL_MASK      ADC_CH_0_MASK | ADC_CH_1_MASK | ADC_CH_2_MASK | ADC_CH_3_MASK | ADC_CH_4_MASK | ADC_CH_5_MASK | ADC_CH_6_MASK| ADC_CH_7_MASK
#define ADC_INPUT_MODE        ADC_INPUT_MODE_SINGLE_END // SINGLE_END, DIFFERENTIAL
#define ADC_OPERATION_MODE    ADC_OPERATION_MODE_CONTINUOUS // SINGLE, SINGLE_CYCLE, CONTINUOUS 
