// mcu
#define MCU_CLOCK_SOURCE
#define MCU_CLOCK_SOURCE_HXT                        // HXT, LXT, HIRC, LIRC
#define MCU_CLOCK_FREQUENCY     50000000            //Hz

// LCD
#define MCU_INTERFACE_SPI3
#define SPI3_CLOCK_SOURCE_HCLK                      // HCLK, PLL
#define SPI3_CLOCK_FREQUENCY    1000000             //Hz
#define PIN_SPI3_SS0_PD8
#define PIN_SPI3_SCLK_PD9
#define PIN_SPI3_MISO0_PD10
#define PIN_SPI3_MOSI0_PD11


// timer 0
#define MCU_INTERFACE_TMR0
#define TMR0_CLOCK_SOURCE_HXT                       // HXT, LXT, HCLK, EXT, LIRC, HIRC
#define TMR0_CLOCK_DIVIDER 1
#define TMR0_OPERATING_MODE TIMER_PERIODIC_MODE     // ONESHOT, PERIODIC, TOGGLE, CONTINUOUS

// timer 1
#define MCU_INTERFACE_TMR1
#define TMR1_CLOCK_SOURCE_HXT
#define TMR1_CLOCK_DIVIDER 1
#define TMR1_OPERATING_MODE TIMER_PERIODIC_MODE
