//Define Clock source
#define MCU_CLOCK_SOURCE      
#define MCU_CLOCK_SOURCE_HXT  // HXT, LXT, HIRC, LIRC
#define MCU_CLOCK_FREQUENCY   50000000  //Hz

//Define MCU Interfaces
// Timer0 as system timer
#define MCU_INTERFACE_TMR0
#define TMR0_CLOCK_SOURCE_HXT // HXT, LXT, HCLK, EXT, LIRC, HIRC
#define TMR0_CLOCK_DIVIDER    1
#define TMR0_OPERATING_MODE   TIMER_PERIODIC_MODE // ONESHOT, PERIODIC, TOGGLE, CONTINUOUS
#define TMR0_OPERATING_FREQ   1000 //Hz = 1ms

// UART to HC05 (Bluetooth)
#define MCU_INTERFACE_UART0
#define UART_CLOCK_SOURCE_HXT // HXT, LXT, PLL, HIRC
#define UART_CLOCK_DIVIDER     3
#define PIN_UART0_RX_PB0
#define PIN_UART0_TX_PB1

// I2C to IMU (MPU6050)
#define MCU_INTERFACE_I2C0
#define I2C0_CLOCK_FREQUENCY  400000 //Hz
#define PIN_I2C0_SCL_PA9 
#define PIN_I2C0_SDA_PA8

// PWM
#define MCU_INTERFACE_PWM0
#define PWM0_CH01_CLOCK_SOURCE_HXT // HXT, LXT, HCLK, HIRC
#define PWM0_CH23_CLOCK_SOURCE_HXT // HXT, LXT, HCLK, HIRC
#define PIN_PWM0_CH0_PA12  
#define PIN_PWM0_CH1_PA13
