#define MCU_CLOCK_SOURCE
#define MCU_CLOCK_SOURCE_HXT
#define MCU_CLOCK_FREQUENCY     50000000


// LCD
#define MCU_INTERFACE_SPI3
#define SPI3_CLOCK_SOURCE_HCLK              // HCLK, PLL
#define SPI3_CLOCK_FREQUENCY    1000000     //Hz
#define PIN_SPI3_SS0_PD8
#define PIN_SPI3_SCLK_PD9
#define PIN_SPI3_MISO0_PD10
#define PIN_SPI3_MOSI0_PD11
