//Define Clock source
#define MCU_CLOCK_SOURCE      
#define MCU_CLOCK_SOURCE_HXT  // HXT, LXT, HIRC, LIRC 
#define MCU_CLOCK_FREQUENCY   48000000  //Hz

//Define MCU Interfaces
#define MCU_INTERFACE_UART1
#define UART_CLOCK_SOURCE_HXT // HXT, PLL, HIRC
#define UART_CLOCK_DIVIDER     3
#define PIN_UART1_RX_PB4
#define PIN_UART1_TX_PB5

#define MCU_INTERFACE_ADC
#define ADC_CLOCK_SOURCE_HXT // HXT, LXT, PLL, HIRC, HCLK
#define ADC_CLOCK_DIVIDER    3
#define PIN_ADC_0
#define PIN_ADC_1
#define PIN_ADC_2
#define PIN_ADC_3
#define PIN_ADC_4
#define PIN_ADC_5
#define PIN_ADC_6
#define PIN_ADC_7
#define ADC_CHANNEL_MASK      ADC_CH_0_MASK | ADC_CH_1_MASK | ADC_CH_2_MASK | ADC_CH_3_MASK | ADC_CH_4_MASK | ADC_CH_5_MASK | ADC_CH_6_MASK| ADC_CH_7_MASK
#define ADC_INPUT_MODE        ADC_INPUT_MODE_SINGLE_END // SINGLE_END, DIFFERENTIAL
#define ADC_OPERATION_MODE    ADC_OPERATION_MODE_CONTINUOUS // SINGLE, SINGLE_CYCLE, CONTINUOUS 
